import { Project, Buyer, Contract } from '../../types';
import { IPAsset } from '../../types/state.types';
import { calculateWeeklyIPRevenue } from '../ip/merchandisingEngine';

/**
 * RevenueProcessor handles all income-related calculations for the studio.
 */
export class RevenueProcessor {
  /**
   * Calculates weekly streaming revenue for a project on a specific platform.
   * Expected: Weekly Licensing Fee = $20,000 (at 100 quality, 10% market share).
   */
  static calculateStreamingRevenue(project: Project, platform: Buyer): number {
    const quality = project.reviewScore || 50;
    const marketShare = platform.marketShare || 0.10;
    
    // Base fee is $2,000 per 1% market share at 100 quality
    const baseFeePerUnit = 2000; 
    const shareUnits = marketShare * 100;
    
    const revenue = baseFeePerUnit * shareUnits * (quality / 100);
    return Math.round(revenue);
  }

  /**
   * Calculates box office decay for a project in a given week.
   */
  static calculateTheatricalDecay(currentRevenue: number, decayRate: number, isCultClassic: boolean = false): number {
    let revenue = Math.round(currentRevenue * decayRate);
    if (isCultClassic) {
      revenue = Math.max(revenue * 1.5, 100000);
    }
    return revenue;
  }

  /**
   * Calculates passive merchandise revenue based on hype and franchise strength.
   */
  static calculateMerchRevenue(hype: number, franchiseRelevance: number): number {
    if (hype < 70) return 0;
    
    // Revenue scales with hype and franchise relevance
    const base = 5000;
    const hypeFactor = (hype - 70) / 30; // 0 to 1
    const relevanceFactor = franchiseRelevance / 100; // 0 to 1
    
    const revenue = base + (base * 5 * hypeFactor * relevanceFactor);
    return Math.round(revenue);
  }

  /**
   * Calculates passive revenue generated by the archived IP vault.
   */
  static calculateVaultDividends(vault: IPAsset[]): number {
    return vault.reduce((total, asset) => total + calculateWeeklyIPRevenue(asset), 0);
  }

  /**
   * Calculates talent royalties (Net Points) for a project.
   * Royalties ONLY trigger after the project has recouped (Total Revenue >= Total Cost).
   */
  static calculateNetPointsRoyalty(project: Project, weeklyRevenue: number, contracts: Contract[]): number {
    const totalCost = project.budget + (project.marketingBudget || 0);
    const totalRevenue = project.revenue || 0;

    // Recoupment check
    if (totalRevenue < totalCost) {
      return 0; // Negative cost has not been recovered yet
    }

    // Payout logic: Gross points based on the current week's revenue
    let totalRoyalty = 0;
    contracts.forEach(contract => {
      if (contract.projectId === project.id && contract.backendPercent > 0) {
        let percent = contract.backendPercent / 100;

        // Backend escalator: +5% if Revenue > 2x Cost
        if (contract.backendEscalator && totalRevenue > totalCost * 2) {
          percent += 0.05;
        }

        totalRoyalty += weeklyRevenue * percent;
      }
    });

    return Math.round(totalRoyalty);
  }
}
