import { pick } from '../utils';

const GENRE_PATTERNS: Record<string, string[][]> = {
  Action: [
    ['The', 'ADJECTIVE', 'NOUN'],
    ['The', 'ADJECTIVE', 'NOUN', 'Protocol'],
    ['Project', 'NOUN', 'Zero'],
    ['NOUN', 'Down'],
    ['VERB', 'or', 'VERB'],
    ['The', 'NAME', 'Ultimatum'],
    ['ADJECTIVE', 'Force'],
    ['Operation', 'ADJECTIVE', 'NOUN'],
    ['NOUN', 'of the', 'PLACE'],
    ['NOUN', 'of', 'NOUN'],
    ['Operation', 'NOUN'],
    ['VERB', 'Hard'],
    ['ADJECTIVE', 'NOUN', 'Protocol'],
    ['The', 'NOUN', 'Cinematic Universe'],
    ['NOUN', 'vs', 'NOUN'],
    ['ADJECTIVE', 'NOUN', ': Origins'],
    ['The', 'ADJECTIVE', 'Franchise'],
    ['Return to', 'PLACE'],
    ['Rebooting the', 'NOUN'],
    ['NOUN', 'Without', 'NOUN'],
    ['ADJECTIVE', 'NOUN', 'Rising'],
    ['Fall of the', 'ADJECTIVE', 'NOUN'],
    ['The', 'NOUN', 'Awakens'],
    ['No Time to', 'VERB'],
    ['Mission:', 'ADJECTIVE'],
    ['Escape from', 'PLACE'],
    ['The', 'NOUN', 'Reckoning']
  ],
  Comedy: [
    ['The', 'ADJECTIVE', 'NOUN'],
    ['Cancel', 'NAME'],
    ['The', 'ADJECTIVE', 'Influencer'],
    ['Trending in', 'PLACE'],
    ['The', 'Meme', 'Team'],
    ['Too', 'ADJECTIVE', 'to', 'VERB'],
    ['My', 'ADJECTIVE', 'Boss'],
    ['The', 'Podcast', 'Disaster'],
    ['VERB', 'Me in', 'PLACE'],
    ['My', 'ADJECTIVE', 'NOUN'],
    ['Don\'t', 'VERB', 'the', 'NOUN'],
    ['NOUN', 'Trouble'],
    ['ADJECTIVE', 'Business'],
    ['Cancel', 'the', 'NOUN'],
    ['ADJECTIVE', 'Content'],
    ['The', 'NOUN', 'Podcast'],
    ['Viral', 'NOUN'],
    ['Trending in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Apology'],
    ['Accidentally', 'ADJECTIVE'],
    ['The', 'NOUN', 'Who', 'VERBS'],
    ['Algorithm', 'Fails'],
    ['Notes App', 'Apology'],
    ['Ratioed in', 'PLACE'],
    ['Main Character', 'Energy'],
    ['Chronically', 'ADJECTIVE']
  ],
  Drama: [
    ['The', 'NOUN', 'of', 'NAME'],
    ['The', 'ADJECTIVE', 'Sociopath'],
    ['Gaslighting', 'NAME'],
    ['Trauma in', 'PLACE'],
    ['The', 'Empath', 'and the', 'NOUN'],
    ['Toxic', 'NOUN'],
    ['Tears of', 'PLACE'],
    ['The', 'Nepotism', 'Paradox'],
    ['Red Flags in', 'PLACE'],
    ['A', 'ADJECTIVE', 'NOUN'],
    ['The', 'NOUN'],
    ['NAME', 'and', 'NAME'],
    ['Echoes', 'of', 'NOUN'],
    ['Trauma in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Sociopath'],
    ['Gaslighting', 'NAME'],
    ['Toxic', 'NOUN'],
    ['The', 'Empath', 'and the', 'NOUN'],
    ['The', 'NOUN', 'We', 'VERB'],
    ['Portrait of a', 'ADJECTIVE', 'NOUN'],
    ['A', 'NOUN', 'in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Lie'],
    ['Unspoken', 'NOUN'],
    ['The', 'NOUN', 'Divide'],
    ['Beneath the', 'NOUN'],
    ['The', 'ADJECTIVE', 'Truth']
  ],
  Horror: [
    ['The', 'NOUN', 'in the', 'PLACE'],
    ['Elevated', 'NOUN'],
    ['The', 'ADJECTIVE', 'Vibe'],
    ['Aesthetic of', 'PLACE'],
    ['Meta', 'NOUN'],
    ['The Subversive', 'NOUN'],
    ['Blood on the', 'NOUN'],
    ['The', 'PLACE', 'Jump Scare'],
    ['Nightmare in', 'PLACE'],
    ['ADJECTIVE', 'NOUN'],
    ['It', 'VERBS', 'at', 'TIME'],
    ['The', 'PLACE'],
    ['Curse of the', 'NOUN'],
    ['Elevated', 'NOUN'],
    ['The', 'ADJECTIVE', 'Vibe'],
    ['Aesthetic of', 'PLACE'],
    ['Meta', 'NOUN'],
    ['The', 'Subversive', 'NOUN'],
    ['The', 'NOUN', 'That', 'VERBS'],
    ['Don\'t', 'VERB'],
    ['The', 'ADJECTIVE', 'Entity'],
    ['Algorithm of', 'Fear'],
    ['The', 'NOUN', 'Paradox'],
    ['Analog', 'NOUN'],
    ['Liminal', 'PLACE'],
    ['The', 'NOUN', 'Project']
  ],
  'Sci-Fi': [
    ['Project', 'NOUN'],
    ['The', 'Metaverse', 'Chronicles'],
    ['Web3', 'NOUN'],
    ['Algorithm of', 'PLACE'],
    ['The', 'ADJECTIVE', 'Simulation'],
    ['Project', 'NOUN'],
    ['The', 'PLACE', 'Singularity'],
    ['Beyond the', 'Algorithm'],
    ['Crypto', 'NOUN'],
    ['The', 'PLACE', 'Chronicles'],
    ['Beyond the', 'PLACE'],
    ['ADJECTIVE', 'Frontier'],
    ['Star', 'NOUN'],
    ['NOUN', ': Part One'],
    ['The', 'Metaverse', 'Chronicles'],
    ['Web3', 'NOUN'],
    ['Algorithm of', 'PLACE'],
    ['The', 'ADJECTIVE', 'Simulation'],
    ['The', 'NOUN', 'Paradigm'],
    ['Echoes from', 'PLACE'],
    ['The', 'ADJECTIVE', 'Machine'],
    ['AI', 'NOUN'],
    ['The', 'NOUN', 'Directive'],
    ['Ghosts in the', 'NOUN'],
    ['The', 'NOUN', 'Anomaly'],
    ['Virtual', 'NOUN']
  ],
  Thriller: [
    ['The', 'ADJECTIVE', 'NOUN'],
    ['The', 'Hacker', 'Identity'],
    ['Exposing', 'NAME'],
    ['The Deepfake', 'Conspiracy'],
    ['Viral', 'Trap'],
    ['Cancelled in', 'PLACE'],
    ['The', 'Grifter', 'Paradox'],
    ['Scamming', 'NAME'],
    ['The', 'ADJECTIVE', 'Whistleblower'],
    ['No', 'NOUN', 'Left'],
    ['Kill', 'the', 'NOUN'],
    ['The', 'NAME', 'Identity'],
    ['Deadly', 'NOUN'],
    ['The', 'Hacker', 'Identity'],
    ['Exposing', 'NAME'],
    ['The', 'Deepfake', 'Conspiracy'],
    ['Viral', 'Trap'],
    ['Cancelled in', 'PLACE'],
    ['The', 'Zero-Day', 'Protocol'],
    ['Breach in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Drop'],
    ['Doxxing', 'NAME'],
    ['Psy-Op', 'Zero'],
    ['The', 'Burner', 'Account'],
    ['Gaslit by the', 'NOUN'],
    ['The', 'NOUN', 'Syndicate']
  ],
  Romance: [
    ['Love in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Heart'],
    ['A', 'NOUN', 'to Remember'],
    ['Meet me at', 'TIME'],
    ['NAME', 'and', 'NAME'],
    ['Ghosting', 'NAME'],
    ['Swiping Right in', 'PLACE'],
    ['The', 'Situationship'],
    ['Toxic', 'Love'],
    ['Match with', 'NAME'],
    ['The', 'Fake Dating', 'Paradox'],
    ['Enemies to', 'NOUN'],
    ['The', 'Slow Burn', 'Summer'],
    ['Hard Launch in', 'PLACE'],
    ['The', 'Green Flag'],
    ['Orbiting', 'NAME'],
    ['The', 'ADJECTIVE', 'Meet-Cute']
  ],
  Animation: [
    ['The', 'ADJECTIVE', 'ANIMAL'],
    ['ANIMAL', 'Tales'],
    ['The Great', 'NOUN', 'Adventure'],
    ['Adventures of', 'NAME'],
    ['Magical', 'PLACE'],
    ['The', 'IP', 'Adventure'],
    ['Synergistic', 'ANIMAL'],
    ['Branded', 'Tales'],
    ['Merch of the', 'NOUN'],
    ['The Marketable', 'ANIMAL'],
    ['The', 'Cash-Grab', 'Chronicles'],
    ['Soulless', 'Sequel'],
    ['The', 'ADJECTIVE', 'Plushie'],
    ['Theme Park', 'Ride:', 'The Movie'],
    ['Cinematic', 'ANIMAL', 'Universe']
  ],
  Documentary: [
    ['The Truth About', 'NOUN'],
    ['Inside the', 'PLACE'],
    ['The', 'NOUN', 'Paradox'],
    ['Rise of the', 'NOUN'],
    ['Uncovering', 'NAME'],
    ['The True Crime of', 'PLACE'],
    ['Cult of', 'NAME'],
    ['Scamming', 'NAME'],
    ['The', 'Grifter', 'Paradox'],
    ['Inside the', 'Algorithm'],
    ['The Fyre Festival of', 'NOUN'],
    ['Exposing the', 'Crypto Crash'],
    ['The', 'ADJECTIVE', 'Charlatan'],
    ['Pyramid Scheme:', 'The', 'NAME', 'Story'],
    ['The', 'Sensationalized', 'Truth'],
    ['Behind the', 'Deepfake']
  ],
  Fantasy: [
    ['The', 'NOUN', 'of', 'PLACE'],
    ['Realm of', 'NOUN'],
    ['The', 'ADJECTIVE', 'King'],
    ['Legends of', 'PLACE'],
    ['The Magic', 'NOUN'],
    ['Lore of', 'PLACE'],
    ['The', 'Canon', 'King'],
    ['Fandom of', 'NOUN'],
    ['The Unofficial', 'Tale'],
    ['Cosplay in', 'PLACE'],
    ['The', 'Grimdark', 'Chronicles'],
    ['Lore of the', 'ADJECTIVE', 'Realm'],
    ['The', 'Problematic', 'Prophecy'],
    ['Gatekeeping the', 'NOUN'],
    ['The', 'Mary-Sue', 'Awakens'],
    ['Headcanon of the', 'ADJECTIVE', 'Elf']
  ],
  Crime: [
    ['The', 'PLACE', 'Murders'],
    ['Blood on the', 'NOUN'],
    ['The', 'NAME', 'Syndicate'],
    ['Heist in', 'PLACE'],
    ['To Catch a', 'NOUN'],
    ['The Crypto', 'Murders'],
    ['Cyber', 'Heist'],
    ['Laundering in', 'PLACE'],
    ['The Anonymous', 'Syndicate'],
    ['Ransomware', 'City'],
    ['The', 'Rug Pull', 'Job'],
    ['Wire Fraud in', 'PLACE'],
    ['The', 'White-Collar', 'Cartel'],
    ['Ponzi Scheme', 'Zero'],
    ['The', 'ADJECTIVE', 'Extortion']
  ],
  Musical: [
    ['Singing in the', 'PLACE'],
    ['The', 'ADJECTIVE', 'Melody'],
    ['Rhythm of', 'PLACE'],
    ['Dance', 'with', 'NAME'],
    ['Song of the', 'NOUN'],
    ['The Jukebox', 'Melody'],
    ['Streaming', 'with', 'NAME'],
    ['Viral', 'Rhythm'],
    ['The Algorithm', 'Dance'],
    ['Platinum', 'Dreams'],
    ['The', 'Industry Plant', 'Story'],
    ['Nepo Baby', 'Sings'],
    ['The', 'Manufactured', 'Popstar'],
    ['Autotune', 'Dreams'],
    ['The', 'Viral', 'TikTok Dance Challenge'],
    ['Overproduced', 'Melodies']
  ]
};

const WORDS: Record<string, string[]> = {
  ADJECTIVE: ['Dark', 'Silent', 'Golden', 'Broken', 'Hidden', 'Last', 'Lost', 'Secret', 'Lethal', 'Final', 'Red', 'Black', 'Wild', 'Crazy', 'Funny', 'Beautiful', 'Brave', 'Fierce', 'Uncut', 'Quantum', 'Cyber', 'Neon', 'Hyper', 'Meta', 'Toxic', 'Viral', 'Cancel', 'Elevated', 'Atmospheric', 'Subversive', 'Procedural', 'Algorithmic', 'Tactical', 'Strategic', 'Covert', 'Clandestine', 'Stealth', 'Phantom', 'Ghost', 'Shadow', 'Rogue', 'Maverick', 'Renegade', 'Outlaw', 'Vigilante', 'Mercenary', 'Expendable', 'Disposable', 'Collateral', 'Fatal', 'Mortal', 'Awkward', 'Cringe', 'Based', 'Woke', 'Problematic', 'Cancelled', 'Triggered', 'Savage', 'Petty', 'Salty', 'Thirsty', 'Basic', 'Extra', 'Bougie', 'Ratchet', 'Sus', 'Cap', 'Overbudget', 'Tone-Deaf', 'Pretentious', 'Self-Indulgent', 'Liminal', 'Uncanny', 'Cash-Grab', 'Soulless', 'Manufactured', 'Algorithm-Approved', 'Tax-Exempt', 'Rebooted', 'Focus-Grouped', 'Monetized', 'Demonetized', 'Post-Credit', 'Data-Driven', 'Derivative', 'Gritty', 'Four-Quadrant', 'Ghostwritten', 'Out-of-Touch', 'Venture-Backed', 'Uncancelled', 'Defamatory', 'AI-Generated', 'Generative', 'Tax-Haven', 'Pivoting',
    // Scribe Expanded Content
    'Derivative', 'Pretentious', 'Subversive', 'Focus-Grouped', 'Algorithmic', 'Gritty', 'Post-Modern', 'Elevated', 'Tax-Deductible', 'Manufactured', 'Self-Indulgent', 'Over-Budget', 'Tone-Deaf', 'Nostalgia-Bait', 'Cash-Grab', 'Venture-Backed', 'Four-Quadrant', 'Demographic-Driven', 'Synergistic', 'Uncanny'
  , 'Algorithm-Driven', 'Corporate-Mandated', 'Focus-Group-Approved', 'Crowdsourced', 'Offshore', 'Tax-Exempt', 'Microtargeted', 'Metrics-Obsessed', 'A/B-Tested', 'Shadow-Banned', 'Engagement-Driven', 'Over-Hyped', 'Review-Bombed', 'Sanitized', 'IP-Driven', 'Subsidized', 'Leveraged', 'Uncredited', 'Ghost-Directed', 'Defunct', 'B-Roll', 'Delisted', 'Generative', 'Synergized', 'Optimized'
  ,
    'Syndicated',
    'Demagnetized',
    'Clickbaity',
    'Ad-Supported',
    'Overlit',
    'Underexposed',
    'Unrelatable',
    'Mid',
    'Try-Hard',
    'Desperate',
    'Narcissistic',
    'Delusional',
    'Memeable',
    'Snarky',
    'Chronically-Online',
    'Gaslighting',
    'Overhyped',
    'Underfunded',
    'Mismanaged',
    'Crowdfunded',
    'Backloaded',
    'Gross-Point',
    // Scribe Adjs
    'Post-Cancellable', 'Metrics-Driven', 'Hyper-Local', 'Transmedia', 'Vertical-Slice', 'Shareholder-Approved', 'Risk-Adjusted', 'Asset-Backed', 'Over-Indexed', 'Pre-Packaged', 'Demographic-Agnostic', 'Cross-Platform', 'Syndication-Ready', 'Merchandisable', 'Franchisable', 'Algorithmic-Optimal', 'Machine-Learned',
    // Showbiz Scribe Daily Additions
    'Tax-Deductible',
    'Algorithm-Optimized',
    'Corporate-Mandated',
    'Focus-Group-Approved',
    'Demographic-Agnostic',
    'Synergistic',
    'Over-Budget',
    'Tone-Deaf',
    'Pretentious',
    'Self-Indulgent',
    'Nostalgia-Bait',
    'Cash-Grab',
    'Four-Quadrant',
    'Metrics-Driven',
    'Market-Researched',
    'Sanitized',
    'IP-Driven',
    'Subsidized',
    'Leveraged',
    'Uncredited',
    'Ghost-Directed',
    'B-Roll',
    'Delisted',
    'Generative',
    'Syndicated',
    'Ad-Supported',
    'Mid',
    'Try-Hard',
    'Desperate',
    'Narcissistic',
    'Chronically-Online',
    'Gaslighting',
    'Overhyped',
    'Underfunded',
    'Mismanaged',
    'Gross-Point',
    'Post-Cancellable',
    'Hyper-Local',
    'Transmedia',
    'Vertical-Slice',
    'Shareholder-Approved',
    'Risk-Adjusted',
    'Asset-Backed',
    'Over-Indexed',
    'Pre-Packaged',
    'Cross-Platform',
    'Syndication-Ready',
    'Merchandisable',
    'Franchisable',
    'Machine-Learned'
  ],
  NOUN: ['Shadow', 'Mirror', 'Ghost', 'Knight', 'City', 'Storm', 'Weapon', 'Target', 'Agent', 'Game', 'House', 'Night', 'Day', 'Star', 'Dream', 'Heart', 'World', 'Man', 'Woman', 'Boy', 'Girl', 'Multiverse', 'Franchise', 'Content', 'Algorithm', 'Meme', 'Podcast', 'Trauma', 'Nepotism', 'Vibe', 'Aesthetic', 'Metaverse', 'Crypto', 'Grifter', 'Situationship', 'IP', 'Recon', 'Extraction', 'Payload', 'Objective', 'Bounty', 'Crossfire', 'Infiltration', 'Exfiltration', 'Takeover', 'Lockdown', 'Overdrive', 'Showdown', 'Blowback', 'Backlash', 'Flashpoint', 'Ground Zero', 'Vanguard', 'Sentinel', 'Outpost', 'Stronghold', 'Influencer', 'Streamer', 'Vlogger', 'Viral', 'Trending', 'Cancel Culture', 'Scam', 'Hustle', 'Flex', 'Clout', 'Drip', 'Mood', 'Energy', 'Synergy', 'Deepfake', 'Blockbuster', 'CGI', 'PR Crisis', 'Apology Video', 'Subtweet', 'Ratio', 'Oscars Bait', 'Method Acting', 'Tax Write-Off', 'Hedge Fund', 'CGI Mush', 'Neomaximalism', 'Engagement Metric', 'Retention Rate', 'Shell Company', 'Tax Haven', 'LLM', 'Zero-Day', 'Psy-Op', 'Astroturf', 'Focus Group', 'NDA', 'Clickfarm', 'Content Farm', 'Brand Deal',
    // Scribe Expanded Content
    'Content', 'Franchise', 'Cinematic Universe', 'Algorithm', 'Focus Group', 'Tax Write-Off', 'Nepo Baby', 'IP', 'Reboot', 'Sequel', 'Prequel', 'Spin-Off', 'Synergy', 'Demographic', 'Engagement', 'Metrics', 'Pitch Deck', 'Boardroom', 'Shareholder', 'Vibe Shift'
  , 'Deliverable', 'Asset', 'Portfolio', 'Ecosystem', 'Pipeline', 'Tax Shelter', 'Shell Corporation', 'Holding', 'Monopoly', 'Subsidiary', 'Data Mine', 'Web3 Venture', 'NFT Collection', 'Demographic', 'Market Research', 'Focus Group', 'Algorithm', 'Deepfake', 'Generative Media', 'Aggregator', 'Synergy', 'Metrics', 'Analytics', 'Content Solution', 'Cartel'
  ,
    'Notes App',
    'Hot Mic',
    'Non-Apology',
    'Stan',
    'Sponsorship',
    'Accountability',
    'Discourse',
    'Generational Wealth',
    'Parasocial Relationship',
    'Syndicate',
    'Regime',
    'Abomination',
    'Cultist',
    'Sacrifice',
    'Hologram',
    'Singularity',
    'NFT Drop',
    'Blockchain',
    'DAO',
    'Metaverse Estate',
    // Scribe Nouns
    'Brand Ecosystem', 'Content Silo', 'Monetization Strategy', 'Value Extraction', 'Strategic Asset', 'Content Portfolio', 'Franchise Management', 'Demographic Target', 'Quarterly Earnings', 'Shareholder Meeting', 'Boardroom Coup', 'Hostile Takeover', 'Merger and Acquisition', 'Tax Loophole', 'NDA Violation', 'PR Spin', 'Damage Control', 'Focus Group Feedback', 'Audience Retention',
    // Showbiz Scribe Daily Additions
    'Tax Write-Off',
    'Nepo Baby',
    'Pitch Deck',
    'Boardroom',
    'Shareholder',
    'Vibe Shift',
    'Deliverable',
    'Asset',
    'Portfolio',
    'Ecosystem',
    'Pipeline',
    'Tax Shelter',
    'Shell Corporation',
    'Holding',
    'Monopoly',
    'Subsidiary',
    'Data Mine',
    'Web3 Venture',
    'NFT Collection',
    'Demographic Target',
    'Market Research',
    'Focus Group Feedback',
    'Algorithm',
    'Deepfake',
    'Generative Media',
    'Aggregator',
    'Synergy',
    'Metrics',
    'Analytics',
    'Content Solution',
    'Cartel',
    'Notes App',
    'Hot Mic',
    'Non-Apology',
    'Stan',
    'Sponsorship',
    'Accountability',
    'Discourse',
    'Generational Wealth',
    'Parasocial Relationship',
    'Syndicate',
    'Regime',
    'Abomination',
    'Cultist',
    'Sacrifice',
    'Hologram',
    'Singularity',
    'NFT Drop',
    'Blockchain',
    'DAO',
    'Metaverse Estate',
    'Brand Ecosystem',
    'Content Silo',
    'Monetization Strategy',
    'Value Extraction',
    'Strategic Asset',
    'Content Portfolio',
    'Franchise Management',
    'Quarterly Earnings',
    'Shareholder Meeting',
    'Boardroom Coup',
    'Hostile Takeover',
    'Merger and Acquisition',
    'Tax Loophole',
    'NDA Violation',
    'PR Spin',
    'Damage Control',
    'Audience Retention'
  ],
  VERB: ['Die', 'Run', 'Shoot', 'Hide', 'Seek', 'Find', 'Kill', 'Save', 'Love', 'Kiss', 'Dance', 'Sing', 'Fly', 'Fall', 'Cancel', 'Reboot', 'Swipe', 'Ghost', 'Stream', 'Hack', 'Leak', 'Trend', 'Post', 'Upload', 'Download', 'Share', 'Like', 'Subscribe', 'Follow', 'Unfollow', 'Block', 'Mute', 'Report', 'Ban', 'Doxx', 'Gaslight', 'Girlboss', 'Gatekeep', 'Manifest', 'Vibe', 'Monetize', 'Synergize', 'Focus-Group', 'Test-Screen', 'A/B Test', 'Ratio', 'Doxx', 'Subtweet', 'Launder', 'Shelve', 'Pivot', 'Astroturf', 'Outsource',
    // Scribe Expanded Content
    'Monetize', 'Synergize', 'Reboot', 'Cancel', 'Pivot', 'Focus-Group', 'Shelve', 'Astroturf', 'Ratio', 'Doxx', 'Launder', 'Outsource', 'Stream', 'Binge', 'Optimize', 'Franchise', 'Leverage', 'Scale'
  , 'Synergize', 'Optimize', 'Leverage', 'Scale', 'Pivot', 'Outsource', 'Astroturf', 'Launder', 'Shelve', 'Focus-Group', 'Test-Screen', 'A/B Test', 'Monetize', 'Franchise', 'Reboot', 'Cancel', 'Ratio', 'Doxx', 'Subtweet', 'Stream', 'Binge', 'Microtarget', 'Shadow-Ban', 'Review-Bomb', 'Crowdsource'
  ,
    'Subsidize',
    'Microdose',
    'Deflect',
    'Project',
    'Spiraling',
    'Manifesting',
    'Vibrating',
    'Demagnetizing',
    'Influencing',
    'Grifting',
    'Hustling',
    'Flexing',
    'Doomscrolling',
    'Trolling',
    'Catfishing',
    'Swiping',
    'Ghosting',
    'Orbiting',
    'Breadcrumbing',
    'Love-Bombing',
    // Scribe Verbs
    'Gamify', 'Syndicate', 'Cross-Promote', 'Divest', 'Liquidate', 'Acquire', 'Merchandize', 'Astroturf', 'Greenwash', 'Pinkwash', 'Retcon', 'Gaslight', 'Girlboss', 'Gatekeep'],
  VERBS: ['Waits', 'Hides', 'Kills', 'Watches', 'Screams', 'Comes', 'Walks', 'Cancels', 'Reboots', 'Swipes', 'Ghosts', 'Streams', 'Hacks', 'Leaks', 'Trends', 'Posts', 'Uploads', 'Downloads', 'Shares', 'Likes', 'Subscribes', 'Follows', 'Unfollows', 'Blocks', 'Mutes', 'Reports', 'Bans', 'Doxxes', 'Gaslights', 'Girlbosses', 'Gatekeeps', 'Manifests', 'Vibes', 'Monetizes', 'Synergizes', 'Focus-Groups', 'Test-Screens', 'A/B Tests', 'Ratios', 'Doxxes', 'Subtweets', 'Launders', 'Shelves', 'Pivots', 'Astroturfs', 'Outsources'],
  PLACE: ['Darkness', 'City', 'Woods', 'Space', 'Future', 'Mars', 'London', 'Paris', 'New York', 'Moon', 'Sun', 'Island', 'Village', 'Metaverse', 'Simulation', 'Web3', 'Timeline', 'Algorithm', 'Feed', 'Grid', 'Matrix', 'Network', 'Cloud', 'Server', 'Database', 'Mainframe', 'Hub', 'Node', 'Nexus', 'Core', 'Vortex', 'Void', 'Abyss', 'Backrooms', 'Discord Server', 'Subreddit', 'TikTok FYP', 'Tax Haven', 'Offshore Account', 'Content Farm', 'Clickfarm', 'Boardroom', 'Focus Group Facility'],
  NAME: ['John', 'Mary', 'Bourne', 'Bond', 'Ripley', 'Neo', 'Trinity', 'Luke', 'Leia', 'Harry', 'Hermione', 'Gatsby', 'Holmes', 'Elon', 'Zuck', 'Chad', 'Karen', 'Influencer', 'Streamer', 'Creator', 'Grifter', 'Scammer', 'Hacker', 'Troll', 'Bot', 'NPC', 'Main Character', 'Side Character', 'Villain', 'Hero', 'Anti-Hero', 'Protagonist', 'Antagonist', 'Nepo Baby', 'Industry Plant', 'Auteur', 'Hedge Fund Manager', 'Venture Capitalist', 'Shareholder', 'CEO', 'Board Member', 'Algorithm'],
  TIME: ['Midnight', 'Dawn', 'Dusk', 'Night', 'Tomorrow', 'Yesterday', 'Upload', 'Drop', 'Stream', 'Post', 'The Golden Hour', 'Crunch Time', 'Q1', 'Q2', 'Q3', 'Q4', 'Fiscal Year', 'Earnings Call', 'Tax Season', 'Zero-Day'],
  ANIMAL: ['Bear', 'Dog', 'Cat', 'Lion', 'Tiger', 'Dragon', 'Unicorn', 'Dinosaur', 'Doge', 'Ape', 'Pepe', 'Capybara', 'Trash Panda', 'Vulture', 'Cash Cow', 'Dead Cat', 'Black Swan']
};

export function generateProjectTitle(genre: string): string {
  const patterns = GENRE_PATTERNS[genre] || GENRE_PATTERNS['Drama'];
  const pattern = pick(patterns);

  return pattern.map(part => {
    if (WORDS[part]) {
      return pick(WORDS[part]);
    }
    return part;
  }).join(' ');
}
