import { RandomGenerator } from '../utils/rng';

const GENRE_PATTERNS: Record<string, string[][]> = {
  Action: [
    ['The', 'ADJECTIVE', 'NOUN'],
    ['The', 'ADJECTIVE', 'NOUN', 'Protocol'],
    ['The', 'ADJECTIVE', 'Cinematic Universe'],
    ['Operation', 'ADJECTIVE', 'Write-Off'],
    ['Project', 'NOUN', 'Zero'],
    ['NOUN', 'Down'],
    ['VERB', 'or', 'VERB'],
    ['The', 'NAME', 'Ultimatum'],
    ['ADJECTIVE', 'Force'],
    ['Operation', 'ADJECTIVE', 'NOUN'],
    ['NOUN', 'of the', 'PLACE'],
    ['NOUN', 'of', 'NOUN'],
    ['Operation', 'NOUN'],
    ['VERB', 'Hard'],
    ['ADJECTIVE', 'NOUN', 'Protocol'],
    ['The', 'NOUN', 'Cinematic Universe'],
    ['NOUN', 'vs', 'NOUN'],
    ['ADJECTIVE', 'NOUN', ': Origins'],
    ['The', 'ADJECTIVE', 'Franchise'],
    ['Return to', 'PLACE'],
    ['Rebooting the', 'NOUN'],
    ['NOUN', 'Without', 'NOUN'],
    ['ADJECTIVE', 'NOUN', 'Rising'],
    ['Fall of the', 'ADJECTIVE', 'NOUN'],
    ['The', 'NOUN', 'Awakens'],
    ['No Time to', 'VERB'],
    ['Mission:', 'ADJECTIVE'],
    ['Escape from', 'PLACE'],
    ['The', 'NOUN', 'Reckoning']
  ],
  Comedy: [
    ['The', 'ADJECTIVE', 'NOUN'],
    ['Cancel', 'NAME'],
    ['The', 'Pre-Packaged', 'NOUN'],
    ['Focus Group', 'NAME'],
    ['The', 'ADJECTIVE', 'Influencer'],
    ['Trending in', 'PLACE'],
    ['The', 'Meme', 'Team'],
    ['Too', 'ADJECTIVE', 'to', 'VERB'],
    ['My', 'ADJECTIVE', 'Boss'],
    ['The', 'Podcast', 'Disaster'],
    ['VERB', 'Me in', 'PLACE'],
    ['My', 'ADJECTIVE', 'NOUN'],
    ['Don\'t', 'VERB', 'the', 'NOUN'],
    ['NOUN', 'Trouble'],
    ['ADJECTIVE', 'Business'],
    ['Cancel', 'the', 'NOUN'],
    ['ADJECTIVE', 'Content'],
    ['The', 'NOUN', 'Podcast'],
    ['Viral', 'NOUN'],
    ['Trending in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Apology'],
    ['Accidentally', 'ADJECTIVE'],
    ['The', 'NOUN', 'Who', 'VERBS'],
    ['Algorithm', 'Fails'],
    ['Notes App', 'Apology'],
    ['Ratioed in', 'PLACE'],
    ['Main Character', 'Energy'],
    ['Chronically', 'ADJECTIVE']
  ],
  Drama: [
    ['The', 'NOUN', 'of', 'NAME'],
    ['The', 'ADJECTIVE', 'Focus Group'],
    ['The', 'Award-Baited', 'NOUN'],
    ['Portrait of a', 'Monetized', 'NAME'],
    ['PR Spin', 'and', 'Damage Control'],
    ['The', 'Shareholder', 'Paradox'],
    ['Tax Write-Off', 'in', 'PLACE'],
    ['The', 'Nepo Baby', 'Dilemma'],
    ['Hostile Takeover'],
    ['The', 'ADJECTIVE', 'Boardroom'],
    ['The', 'NDA Violation'],
    ['Metrics', 'and', 'Men'],
    ['Generational Wealth', 'in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Apology Video'],
    ['Notes App', 'Tears'],
    ['The', 'Vibe Shift'],
    ['Quarterly Earnings'],
    ['The', 'ADJECTIVE', 'Sociopath'],
    ['Gaslighting', 'NAME'],
    ['Trauma in', 'PLACE'],
    ['The', 'Empath', 'and the', 'NOUN'],
    ['Toxic', 'NOUN'],
    ['Tears of', 'PLACE'],
    ['The', 'Nepotism', 'Paradox'],
    ['Red Flags in', 'PLACE'],
    ['A', 'ADJECTIVE', 'NOUN'],
    ['The', 'NOUN'],
    ['NAME', 'and', 'NAME'],
    ['Echoes', 'of', 'NOUN'],
    ['Portrait of a', 'ADJECTIVE', 'NOUN'],
    ['A', 'NOUN', 'in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Lie'],
    ['Unspoken', 'NOUN'],
    ['The', 'NOUN', 'Divide'],
    ['Beneath the', 'NOUN'],
    ['The', 'ADJECTIVE', 'Truth']
  ],
  Horror: [
    ['The', 'NOUN', 'in the', 'PLACE'],
    ['Elevated', 'NOUN'],
    ['The', 'Focus-Tested', 'Entity'],
    ['A', 'Four-Quadrant', 'Nightmare'],
    ['The', 'ADJECTIVE', 'Vibe'],
    ['Aesthetic of', 'PLACE'],
    ['Meta', 'NOUN'],
    ['The Subversive', 'NOUN'],
    ['Blood on the', 'NOUN'],
    ['The', 'PLACE', 'Jump Scare'],
    ['Nightmare in', 'PLACE'],
    ['ADJECTIVE', 'NOUN'],
    ['It', 'VERBS', 'at', 'TIME'],
    ['The', 'PLACE'],
    ['Curse of the', 'NOUN'],
    ['The', 'NOUN', 'That', 'VERBS'],
    ['Don\'t', 'VERB'],
    ['The', 'ADJECTIVE', 'Entity'],
    ['Algorithm of', 'Fear'],
    ['The', 'NOUN', 'Paradox'],
    ['Analog', 'NOUN'],
    ['Liminal', 'PLACE'],
    ['The', 'NOUN', 'Project']
  ],
  'Sci-Fi': [
    ['Project', 'NOUN'],
    ['The', 'ADJECTIVE', 'Algorithm'],
    ['The', 'NFT', 'Protocol'],
    ['A', 'Generative', 'PLACE'],
    ['Generative', 'NOUN'],
    ['Beyond the', 'Data Mine'],
    ['The', 'Web3', 'Incident'],
    ['Deepfake', 'Chronicles'],
    ['The', 'Content Solution'],
    ['Project', 'Synergy'],
    ['The', 'Ecosystem'],
    ['NFT Collection', 'Zero'],
    ['The', 'ADJECTIVE', 'Aggregator'],
    ['Machine-Learned', 'Love'],
    ['The', 'Cross-Platform', 'Entity'],
    ['The', 'Metaverse', 'Chronicles'],
    ['Web3', 'NOUN'],
    ['Algorithm of', 'PLACE'],
    ['The', 'ADJECTIVE', 'Simulation'],
    ['The', 'PLACE', 'Singularity'],
    ['Beyond the', 'Algorithm'],
    ['Crypto', 'NOUN'],
    ['ADJECTIVE', 'Frontier'],
    ['Star', 'NOUN'],
    ['NOUN', ': Part One'],
    ['The', 'NOUN', 'Paradigm'],
    ['Echoes from', 'PLACE'],
    ['The', 'ADJECTIVE', 'Machine'],
    ['AI', 'NOUN'],
    ['The', 'NOUN', 'Directive'],
    ['Ghosts in the', 'NOUN'],
    ['The', 'NOUN', 'Anomaly'],
    ['Virtual', 'NOUN']
  ],
  Thriller: [
    ['The', 'ADJECTIVE', 'NOUN'],
    ['The', 'Hacker', 'Identity'],
    ['Exposing', 'NAME'],
    ['The Deepfake', 'Conspiracy'],
    ['Viral', 'Trap'],
    ['Cancelled in', 'PLACE'],
    ['The', 'Grifter', 'Paradox'],
    ['Scamming', 'NAME'],
    ['The', 'ADJECTIVE', 'Whistleblower'],
    ['No', 'NOUN', 'Left'],
    ['Kill', 'the', 'NOUN'],
    ['The', 'NAME', 'Identity'],
    ['Deadly', 'NOUN'],
    ['The', 'Zero-Day', 'Protocol'],
    ['Breach in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Drop'],
    ['Doxxing', 'NAME'],
    ['Psy-Op', 'Zero'],
    ['The', 'Burner', 'Account'],
    ['Gaslit by the', 'NOUN'],
    ['The', 'NOUN', 'Syndicate']
  ],
  Romance: [
    ['Love in', 'PLACE'],
    ['The', 'ADJECTIVE', 'Heart'],
    ['A', 'NOUN', 'to Remember'],
    ['Meet me at', 'TIME'],
    ['NAME', 'and', 'NAME'],
    ['Ghosting', 'NAME'],
    ['Swiping Right in', 'PLACE'],
    ['The', 'Situationship'],
    ['Toxic', 'Love'],
    ['Match with', 'NAME'],
    ['The', 'Fake Dating', 'Paradox'],
    ['Enemies to', 'NOUN'],
    ['The', 'Slow Burn', 'Summer'],
    ['Hard Launch in', 'PLACE'],
    ['The', 'Green Flag'],
    ['Orbiting', 'NAME'],
    ['The', 'ADJECTIVE', 'Meet-Cute']
  ],
  Animation: [
    ['The', 'ADJECTIVE', 'ANIMAL'],
    ['ANIMAL', 'Tales'],
    ['The Great', 'NOUN', 'Adventure'],
    ['Adventures of', 'NAME'],
    ['Magical', 'PLACE'],
    ['The', 'IP', 'Adventure'],
    ['Synergistic', 'ANIMAL'],
    ['Branded', 'Tales'],
    ['Merch of the', 'NOUN'],
    ['The Marketable', 'ANIMAL'],
    ['The', 'Cash-Grab', 'Chronicles'],
    ['Soulless', 'Sequel'],
    ['The', 'ADJECTIVE', 'Plushie'],
    ['Theme Park', 'Ride:', 'The Movie'],
    ['Cinematic', 'ANIMAL', 'Universe']
  ],
  Documentary: [
    ['The Truth About', 'NOUN'],
    ['Inside the', 'PLACE'],
    ['The', 'NOUN', 'Paradox'],
    ['Rise of the', 'NOUN'],
    ['Uncovering', 'NAME'],
    ['The True Crime of', 'PLACE'],
    ['Cult of', 'NAME'],
    ['Scamming', 'NAME'],
    ['The', 'Grifter', 'Paradox'],
    ['Inside the', 'Algorithm'],
    ['The Fyre Festival of', 'NOUN'],
    ['Exposing the', 'Crypto Crash'],
    ['The', 'ADJECTIVE', 'Charlatan'],
    ['Pyramid Scheme:', 'The', 'NAME', 'Story'],
    ['The', 'Sensationalized', 'Truth'],
    ['Behind the', 'Deepfake']
  ],
  Fantasy: [
    ['The', 'NOUN', 'of', 'PLACE'],
    ['Realm of', 'NOUN'],
    ['The', 'ADJECTIVE', 'King'],
    ['Legends of', 'PLACE'],
    ['The Magic', 'NOUN'],
    ['Lore of', 'PLACE'],
    ['The', 'Canon', 'King'],
    ['Fandom of', 'NOUN'],
    ['The Unofficial', 'Tale'],
    ['Cosplay in', 'PLACE'],
    ['The', 'Grimdark', 'Chronicles'],
    ['Lore of the', 'ADJECTIVE', 'Realm'],
    ['The', 'Problematic', 'Prophecy'],
    ['Gatekeeping the', 'NOUN'],
    ['The', 'Mary-Sue', 'Awakens'],
    ['Headcanon of the', 'ADJECTIVE', 'Elf']
  ],
  Crime: [
    ['The', 'PLACE', 'Murders'],
    ['Blood on the', 'NOUN'],
    ['The', 'NAME', 'Syndicate'],
    ['Heist in', 'PLACE'],
    ['To Catch a', 'NOUN'],
    ['The Crypto', 'Murders'],
    ['Cyber', 'Heist'],
    ['Laundering in', 'PLACE'],
    ['The Anonymous', 'Syndicate'],
    ['Ransomware', 'City'],
    ['The', 'Rug Pull', 'Job'],
    ['Wire Fraud in', 'PLACE'],
    ['The', 'White-Collar', 'Cartel'],
    ['Ponzi Scheme', 'Zero'],
    ['The', 'ADJECTIVE', 'Extortion']
  ],
  Musical: [
    ['Singing in the', 'PLACE'],
    ['The', 'ADJECTIVE', 'Melody'],
    ['Rhythm of', 'PLACE'],
    ['Dance', 'with', 'NAME'],
    ['Song of the', 'NOUN'],
    ['The Jukebox', 'Melody'],
    ['Streaming', 'with', 'NAME'],
    ['Viral', 'Rhythm'],
    ['The Algorithm', 'Dance'],
    ['Platinum', 'Dreams'],
    ['The', 'Industry Plant', 'Story'],
    ['Nepo Baby', 'Sings'],
    ['The', 'Manufactured', 'Popstar'],
    ['Autotune', 'Dreams'],
    ['The', 'Viral', 'TikTok Dance Challenge'],
    ['Overproduced', 'Melodies']
  ]
};

const WORDS: Record<string, string[]> = {
  ADJECTIVE: ['Dark', 'Silent', 'Golden', 'Broken', 'Hidden', 'Last', 'Lost', 'Secret', 'Lethal', 'Final', 'Red', 'Black', 'Wild', 'Crazy', 'Funny', 'Beautiful', 'Brave', 'Fierce', 'Uncut', 'Quantum', 'Cyber', 'Neon', 'Hyper', 'Meta', 'Toxic', 'Viral', 'Cancel', 'Elevated', 'Atmospheric', 'Subversive', 'Procedural', 'Algorithmic', 'Tactical', 'Strategic', 'Covert', 'Clandestine', 'Stealth', 'Phantom', 'Ghost', 'Shadow', 'Rogue', 'Maverick', 'Renegade', 'Outlaw', 'Vigilante', 'Mercenary', 'Expendable', 'Disposable', 'Collateral', 'Fatal', 'Mortal', 'Awkward', 'Cringe', 'Based', 'Woke', 'Problematic', 'Cancelled', 'Triggered', 'Savage', 'Petty', 'Salty', 'Thirsty', 'Basic', 'Extra', 'Bougie', 'Ratchet', 'Sus', 'Cap', 'Overbudget', 'Tone-Deaf', 'Pretentious', 'Self-Indulgent', 'Liminal', 'Uncanny', 'Cash-Grab', 'Soulless', 'Manufactured', 'Algorithm-Approved', 'Tax-Exempt', 'Rebooted', 'Focus-Grouped', 'Monetized', 'Demonetized', 'Post-Credit', 'Data-Driven', 'Derivative', 'Gritty', 'Four-Quadrant', 'Ghostwritten', 'Out-of-Touch', 'Venture-Backed', 'Uncancelled', 'Defamatory', 'AI-Generated', 'Generative', 'Tax-Haven', 'Pivoting',
    'Post-Cancellable', 'Metrics-Driven', 'Hyper-Local', 'Transmedia', 'Vertical-Slice', 'Shareholder-Approved', 'Risk-Adjusted', 'Asset-Backed', 'Over-Indexed', 'Pre-Packaged', 'Demographic-Agnostic', 'Cross-Platform', 'Syndication-Ready', 'Merchandisable', 'Franchisable', 'Algorithmic-Optimal', 'Machine-Learned', 'Focus-Tested', 'Sanitized', 'Corporate-Mandated', 'Data-Mined', 'Merch-Driven', 'Tax-Writeoff', 'Laundered', 'Market-Tested', 'Brand-Safe', 'CGI-Heavy',
    'Bingeable', 'Non-Union', 'Subsidized', 'Franchise-Ready', 'Syndicated'
  ],
  NOUN: ['Shadow', 'Mirror', 'Ghost', 'Knight', 'City', 'Storm', 'Weapon', 'Target', 'Agent', 'Game', 'House', 'Night', 'Day', 'Star', 'Dream', 'Heart', 'World', 'Man', 'Woman', 'Boy', 'Girl', 'Multiverse', 'Franchise', 'Content', 'Algorithm', 'Meme', 'Podcast', 'Trauma', 'Nepotism', 'Vibe', 'Aesthetic', 'Metaverse', 'Crypto', 'Grifter', 'Situationship', 'IP', 'Recon', 'Extraction', 'Payload', 'Objective', 'Bounty', 'Crossfire', 'Infiltration', 'Exfiltration', 'Takeover', 'Lockdown', 'Overdrive', 'Showdown', 'Blowback', 'Backlash', 'Flashpoint', 'Ground Zero', 'Vanguard', 'Sentinel', 'Outpost', 'Stronghold', 'Influencer', 'Streamer', 'Vlogger', 'Viral', 'Trending', 'Cancel Culture', 'Scam', 'Hustle', 'Flex', 'Clout', 'Drip', 'Mood', 'Energy', 'Synergy', 'Deepfake', 'Blockbuster', 'CGI', 'PR Crisis', 'Apology Video', 'Subtweet', 'Ratio', 'Oscars Bait', 'Method Acting', 'Tax Write-Off', 'Hedge Fund', 'CGI Mush', 'Neomaximalism', 'Engagement Metric', 'Retention Rate', 'Shell Company', 'Tax Haven', 'LLM', 'Zero-Day', 'Psy-Op', 'Astroturf', 'Focus Group', 'NDA', 'Clickfarm', 'Content Farm', 'Brand Deal',
    'Brand Ecosystem', 'Content Silo', 'Monetization Strategy', 'Value Extraction', 'Strategic Asset', 'Content Portfolio', 'Franchise Management', 'Demographic Target', 'Quarterly Earnings', 'Shareholder Meeting', 'Boardroom Coup', 'Hostile Takeover', 'Merger and Acquisition', 'Tax Loophole', 'NDA Violation', 'PR Spin', 'Damage Control', 'Focus Group Feedback', 'Audience Retention', 'CGI Void', 'Post-Credit Scene', 'Cinematic Universe', 'Merchandising Rights', 'Test Audience', 'Algorithm Spike', 'A.I. Artifact', 'Studio Mandate', 'Box Office Flop', 'Tax Shelter',
    'Focus-Group Participant', 'Brand Identity', 'Product Placement', 'Merger', 'Acquisition'
  ],
  VERB: ['Die', 'Run', 'Shoot', 'Hide', 'Seek', 'Find', 'Kill', 'Save', 'Love', 'Kiss', 'Dance', 'Sing', 'Fly', 'Fall', 'Cancel', 'Reboot', 'Swipe', 'Ghost', 'Stream', 'Hack', 'Leak', 'Trend', 'Post', 'Upload', 'Download', 'Share', 'Like', 'Subscribe', 'Follow', 'Unfollow', 'Block', 'Mute', 'Report', 'Ban', 'Doxx', 'Gaslight', 'Girlboss', 'Gatekeep', 'Manifest', 'Vibe', 'Monetize', 'Synergize', 'Focus-Group', 'Test-Screen', 'A/B Test', 'Ratio', 'Doxx', 'Subtweet', 'Launder', 'Shelve', 'Pivot', 'Astroturf', 'Outsource',
    'Gamify', 'Syndicate', 'Cross-Promote', 'Divest', 'Liquidate', 'Acquire', 'Merchandize', 'Astroturf', 'Greenwash', 'Pinkwash', 'Retcon', 'Gaslight', 'Girlboss', 'Gatekeep',
    'Consolidate', 'Restructure', 'Depreciate', 'Overextend', 'Underperform'],
  VERBS: ['Waits', 'Hides', 'Kills', 'Watches', 'Screams', 'Comes', 'Walks', 'Cancels', 'Reboots', 'Swipes', 'Ghosts', 'Streams', 'Hacks', 'Leaks', 'Trends', 'Posts', 'Uploads', 'Downloads', 'Shares', 'Likes', 'Subscribes', 'Follows', 'Unfollows', 'Blocks', 'Mutes', 'Reports', 'Bans', 'Doxxes', 'Gaslights', 'Girlbosses', 'Gatekeeps', 'Manifests', 'Vibes', 'Monetizes', 'Synergizes', 'Focus-Groups', 'Test-Screens', 'A/B Tests', 'Ratios', 'Doxxes', 'Subtweets', 'Launders', 'Shelves', 'Pivots', 'Astroturfs', 'Outsources',
    'Consolidates', 'Restructures', 'Depreciates', 'Overextends', 'Underperforms'],
  PLACE: ['Darkness', 'City', 'Woods', 'Space', 'Future', 'Mars', 'London', 'Paris', 'New York', 'Moon', 'Sun', 'Island', 'Village', 'Metaverse', 'Simulation', 'Web3', 'Timeline', 'Algorithm', 'Feed', 'Grid', 'Matrix', 'Network', 'Cloud', 'Server', 'Database', 'Mainframe', 'Hub', 'Node', 'Nexus', 'Core', 'Vortex', 'Void', 'Abyss', 'Backrooms', 'Discord Server', 'Subreddit', 'TikTok FYP', 'Tax Haven', 'Offshore Account', 'Content Farm', 'Clickfarm', 'Boardroom', 'Focus Group Facility',
    'The Write-Off Bin', 'The Streaming Vault', 'The Data Center', 'The LLC'],
  NAME: ['John', 'Mary', 'Bourne', 'Bond', 'Ripley', 'Neo', 'Trinity', 'Luke', 'Leia', 'Harry', 'Hermione', 'Gatsby', 'Holmes', 'Elon', 'Zuck', 'Chad', 'Karen', 'Influencer', 'Streamer', 'Creator', 'Grifter', 'Scammer', 'Hacker', 'Troll', 'Bot', 'NPC', 'Main Character', 'Side Character', 'Villain', 'Hero', 'Anti-Hero', 'Protagonist', 'Antagonist', 'Nepo Baby', 'Industry Plant', 'Auteur', 'Hedge Fund Manager', 'Venture Capitalist', 'Shareholder', 'CEO', 'Board Member', 'Algorithm',
    'The VP of Content', 'The IP Lawyer', 'The Brand Manager', 'The Private Equity Firm'],
  TIME: ['Midnight', 'Dawn', 'Dusk', 'Night', 'Tomorrow', 'Yesterday', 'Upload', 'Drop', 'Stream', 'Post', 'The Golden Hour', 'Crunch Time', 'Q1', 'Q2', 'Q3', 'Q4', 'Fiscal Year', 'Earnings Call', 'Tax Season', 'Zero-Day'],
  ANIMAL: ['Bear', 'Dog', 'Cat', 'Lion', 'Tiger', 'Dragon', 'Unicorn', 'Dinosaur', 'Doge', 'Ape', 'Pepe', 'Capybara', 'Trash Panda', 'Vulture', 'Cash Cow', 'Dead Cat', 'Black Swan']
};

export function generateProjectTitle(genre: string, rng: RandomGenerator): string {
  const patterns = GENRE_PATTERNS[genre] || GENRE_PATTERNS['Drama'];
  const pattern = rng.pick(patterns);

  return pattern.map((part: string) => {
    if (WORDS[part]) {
      return rng.pick(WORDS[part]);
    }
    return part;
  }).join(' ');
}
