import { GameState, StateImpact } from "@/engine/types";
import { ProducerShingle } from "@/engine/types/talent.types";
import { RandomGenerator } from "@/engine/utils/rng";

/**
 * ShinglePitchRouter — routes pitches generated by a shingle to the contract studio.
 *
 * The simulation currently tracks project creation through other pipelines (AI + player
 * greenlight flow), so this router is a light-weight overlay: it emits a pitch event,
 * the contract studio decides accept / pass per deal type, and the router logs the
 * outcome for the 50-year report. No real `Project` entity is created — the pipe
 * exists to measure shingle throughput + pass-through behavior against the targets.
 */

export interface ShinglePitchOutcome {
  week: number;
  year: number;
  shingleId: string;
  shingleName: string;
  ownerName: string;
  originalStudioId: string | null;
  originalStudioName: string;
  finalStudioId: string | null;
  finalStudioName: string;
  accepted: boolean;
  passed: boolean;
  dealType: string;
  note?: string;
}

export const pitchOutcomeLog: ShinglePitchOutcome[] = [];

export function resetPitchState() {
  pitchOutcomeLog.length = 0;
}

function yearFromWeek(week: number): number {
  return 1975 + Math.floor(week / 52);
}

function getStudioName(state: GameState, studioId: string | null): string {
  if (!studioId) return "open market";
  if (studioId === state.studio.id) return state.studio?.name || "Player Studio";
  return state.entities.rivals[studioId]?.name || studioId;
}

function shinglePitchRate(s: ProducerShingle, ownerPrestige: number): number {
  // 1-3 pitches per year ~= 0.02-0.06 per week. Top owners pitch more often.
  const base = 0.025 + Math.max(0, ownerPrestige - 60) / 2000;
  return Math.min(0.07, base);
}

function studioInDistressStage3Plus(state: GameState, studioId: string): boolean {
  if (studioId === state.studio.id) return false;
  const r = state.entities.rivals[studioId];
  if (!r) return true;
  return (r.cash || 0) < -200_000_000;
}

function studioDecides(
  state: GameState,
  shingle: ProducerShingle,
  studioId: string,
  rng: RandomGenerator
): { accept: boolean; reason: string } {
  if (shingle.dealType === "OVERALL" || shingle.dealType === "POD") {
    if (studioInDistressStage3Plus(state, studioId))
      return { accept: false, reason: "distress-exit" };
    return { accept: true, reason: "overall-mandate" };
  }
  // Bucket C: NPC AI heuristic — accept if cash > overhead*20 and project fit is strong.
  // Fit proxies: owner prestige (higher = better fit) + macro/genre heat (skipped for now — owner
  // prestige captures most of the signal for the pass-through router).
  const cash =
    studioId === state.studio.id
      ? state.finance.cash || 0
      : state.entities.rivals[studioId]?.cash || 0;
  const owner = state.entities.talents[shingle.ownerTalentId];
  const ownerPrestige = owner?.prestige || 0;
  const overhead = shingle.overheadPerYear || 1;
  const cashGate = cash > overhead * 20;
  // Fit score: 0-1, derived from talent prestige (>50 = solid pitch, >75 = marquee).
  const fitScore = Math.min(1, Math.max(0, (ownerPrestige - 30) / 50));
  const fitGate = fitScore > 0.25;

  if (shingle.dealType === "FIRST_LOOK") {
    if (!cashGate) return { accept: false, reason: "first-look-cash-gate" };
    if (!fitGate) return { accept: false, reason: "first-look-fit-gate" };
    // Soft accept: rich studio + good fit => ~70%+, marginal => ~35%.
    const prob = 0.45 + fitScore * 0.4;
    return { accept: rng.next() < prob, reason: "first-look-yes-heuristic" };
  }
  // HOUSEKEEPING: loose dev deal; accept more readily when cash is fine.
  const prob = cashGate ? 0.3 + fitScore * 0.2 : 0.1;
  return { accept: rng.next() < prob, reason: "housekeeping-heuristic" };
}

function openMarketBuyer(
  state: GameState,
  rng: RandomGenerator,
  excludeId: string | null
): string | null {
  const candidates: string[] = [];
  if (excludeId !== state.studio.id && (state.finance.cash || 0) > 100_000_000)
    candidates.push(state.studio.id);
  // ⚡ The Framerate Fanatic: Replaced Object.values() with a direct for...in loop
  const rivals = state.entities.rivals || {};
  for (const id in rivals) {
    const r = rivals[id];
    if (r.id === excludeId) continue;
    if ((r.cash || 0) > 100_000_000) candidates.push(r.id);
  }
  if (candidates.length === 0) return null;
  return rng.pick(candidates);
}

export function tickShinglePitchRouter(state: GameState, rng: RandomGenerator): StateImpact[] {
  const impacts: StateImpact[] = [];
  // ⚡ The Framerate Fanatic: Replaced Object.values() with a direct for...in loop
  const shingles = state.entities.shingles || {};
  for (const shingleId in shingles) {
    const s = shingles[shingleId];
    const owner = state.entities.talents[s.ownerTalentId];
    if (!owner) continue;
    const rate = shinglePitchRate(s, owner.prestige || 0);
    if (rng.next() > rate) continue;

    // Bump pitch counter.
    const pitched = (s.pitchesGenerated || 0) + 1;
    let accepted = 0;
    let finalStudio: string | null = s.baseStudioId;
    let passed = false;
    let note: string | undefined;

    if (!s.baseStudioId) {
      // Free agent — shop open market.
      finalStudio = openMarketBuyer(state, rng, null);
      if (finalStudio) {
        accepted = 1;
        note = "free-agent-open-market";
      } else {
        passed = true;
        note = "no-open-market-buyer";
      }
    } else {
      const decision = studioDecides(state, s, s.baseStudioId, rng);
      if (decision.accept) {
        accepted = 1;
        note = decision.reason;
      } else if (s.dealType === "FIRST_LOOK" || s.dealType === "HOUSEKEEPING") {
        // Studio passes — pitch open market.
        const buyer = openMarketBuyer(state, rng, s.baseStudioId);
        if (buyer) {
          finalStudio = buyer;
          accepted = 1;
          note = `pass-through from ${getStudioName(state, s.baseStudioId)}`;
        } else {
          passed = true;
          note = "passed, no open-market buyer";
        }
      } else {
        // OVERALL/POD rare-exit: counts as a pass under heavy distress.
        passed = true;
        note = decision.reason;
      }
    }

    pitchOutcomeLog.push({
      week: state.week,
      year: yearFromWeek(state.week),
      shingleId: s.id,
      shingleName: s.name,
      ownerName: owner.name,
      originalStudioId: s.baseStudioId,
      originalStudioName: getStudioName(state, s.baseStudioId),
      finalStudioId: finalStudio,
      finalStudioName: getStudioName(state, finalStudio),
      accepted: accepted > 0,
      passed,
      dealType: s.dealType,
      note,
    });

    impacts.push({
      type: "SHINGLE_UPDATED",
      payload: {
        shingleId: s.id,
        update: {
          pitchesGenerated: pitched,
          pitchesAccepted: (s.pitchesAccepted || 0) + accepted,
          lastPitchWeek: state.week,
        },
      },
    } as unknown as StateImpact);
  }
  return impacts;
}
