import { IPAsset } from '../../types/state.types';
import { getSyndicationImpact } from './syndicationEngine';

/**
 * Calculates passive revenue generated by an IP Asset.
 * This includes merchandising and television syndication fees.
 */
export function calculateWeeklyIPRevenue(asset: IPAsset): number {
  if (asset.decayRate <= 0.05) return 0; // Culturally "dead" IP

  // Base merchandising logic: (Value * Multiplier) scaled by current relevance (decayRate)
  let merchRevenue = (asset.baseValue * asset.merchandisingMultiplier) * asset.decayRate;

  // Syndication Logic: Tiered multipliers replace binary check
  // Gold = 3.5x, Silver = 2.2x, Bronze = 1.4x
  const impact = getSyndicationImpact(asset.syndicationTier);
  
  if (asset.syndicationTier !== 'NONE') {
    // Syndication provides a high floor of revenue (percentage of base value)
    const syndicationFloor = asset.baseValue * 0.05 * impact.revenueMultiplier;
    merchRevenue = (merchRevenue * impact.revenueMultiplier) + syndicationFloor;
  }

  return Math.floor(merchRevenue);
}
